SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT * FROM covid_cases WHERE Country = 'India';

START TRANSACTION;
UPDATE covid_cases SET Confirmed_Cases = 20000000 WHERE Country = 'India' AND Date = '2021-05-01';

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
START TRANSACTION;
SELECT * FROM covid_cases WHERE Country = 'India';

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
START TRANSACTION;
SELECT * FROM covid_cases WHERE Confirmed_Cases > 10000000;
COMMIT;